/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ActionMetadata
 */
class ActionMetadataTest {
    private final ActionMetadata model = new ActionMetadata();

    /**
     * Model tests for ActionMetadata
     */
    @Test
    void testActionMetadata() {
        // TODO: test ActionMetadata
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'icon'
     */
    @Test
    void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'group'
     */
    @Test
    void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'renderer'
     */
    @Test
    void rendererTest() {
        // TODO: test renderer
    }

    /**
     * Test the property 'applicableClasses'
     */
    @Test
    void applicableClassesTest() {
        // TODO: test applicableClasses
    }

    /**
     * Test the property 'applicableStates'
     */
    @Test
    void applicableStatesTest() {
        // TODO: test applicableStates
    }

}
