/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ActionExecutionRequest
 */
class ActionExecutionRequestTest {
    private final ActionExecutionRequest model = new ActionExecutionRequest();

    /**
     * Model tests for ActionExecutionRequest
     */
    @Test
    void testActionExecutionRequest() {
        // TODO: test ActionExecutionRequest
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'params'
     */
    @Test
    void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'dataId'
     */
    @Test
    void dataIdTest() {
        // TODO: test dataId
    }

    /**
     * Test the property 'dataName'
     */
    @Test
    void dataNameTest() {
        // TODO: test dataName
    }

}
