/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tools.dynamia.clients.model.EntityMetadata;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApplicationMetadataEntities
 */
class ApplicationMetadataEntitiesTest {
    private final ApplicationMetadataEntities model = new ApplicationMetadataEntities();

    /**
     * Model tests for ApplicationMetadataEntities
     */
    @Test
    void testApplicationMetadataEntities() {
        // TODO: test ApplicationMetadataEntities
    }

    /**
     * Test the property 'entities'
     */
    @Test
    void entitiesTest() {
        // TODO: test entities
    }

}
