/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BeanSorterObject
 */
class BeanSorterObjectTest {
    private final BeanSorterObject model = new BeanSorterObject();

    /**
     * Model tests for BeanSorterObject
     */
    @Test
    void testBeanSorterObject() {
        // TODO: test BeanSorterObject
    }

    /**
     * Test the property 'ascending'
     */
    @Test
    void ascendingTest() {
        // TODO: test ascending
    }

    /**
     * Test the property 'columnName'
     */
    @Test
    void columnNameTest() {
        // TODO: test columnName
    }

}
