/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DataPaginator
 */
class DataPaginatorTest {
    private final DataPaginator model = new DataPaginator();

    /**
     * Model tests for DataPaginator
     */
    @Test
    void testDataPaginator() {
        // TODO: test DataPaginator
    }

    /**
     * Test the property 'totalSize'
     */
    @Test
    void totalSizeTest() {
        // TODO: test totalSize
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'firstResult'
     */
    @Test
    void firstResultTest() {
        // TODO: test firstResult
    }

    /**
     * Test the property 'page'
     */
    @Test
    void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pagesNumber'
     */
    @Test
    void pagesNumberTest() {
        // TODO: test pagesNumber
    }

}
