/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FieldGroup
 */
class FieldGroupTest {
    private final FieldGroup model = new FieldGroup();

    /**
     * Model tests for FieldGroup
     */
    @Test
    void testFieldGroup() {
        // TODO: test FieldGroup
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'label'
     */
    @Test
    void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'icon'
     */
    @Test
    void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'index'
     */
    @Test
    void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'collapse'
     */
    @Test
    void collapseTest() {
        // TODO: test collapse
    }

    /**
     * Test the property 'params'
     */
    @Test
    void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'localizedLabel'
     */
    @Test
    void localizedLabelTest() {
        // TODO: test localizedLabel
    }

    /**
     * Test the property 'fields'
     */
    @Test
    void fieldsTest() {
        // TODO: test fields
    }

}
