/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NavigationNode
 */
class NavigationNodeTest {
    private final NavigationNode model = new NavigationNode();

    /**
     * Model tests for NavigationNode
     */
    @Test
    void testNavigationNode() {
        // TODO: test NavigationNode
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'longName'
     */
    @Test
    void longNameTest() {
        // TODO: test longName
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'icon'
     */
    @Test
    void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'internalPath'
     */
    @Test
    void internalPathTest() {
        // TODO: test internalPath
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'position'
     */
    @Test
    void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'featured'
     */
    @Test
    void featuredTest() {
        // TODO: test featured
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property '_file'
     */
    @Test
    void _fileTest() {
        // TODO: test _file
    }

}
