/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import tools.dynamia.clients.model.BeanSorterObject;
import tools.dynamia.clients.model.DataPaginator;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryParameters
 */
class QueryParametersTest {
    private final QueryParameters model = new QueryParameters();

    /**
     * Model tests for QueryParameters
     */
    @Test
    void testQueryParameters() {
        // TODO: test QueryParameters
    }

    /**
     * Test the property 'sorter'
     */
    @Test
    void sorterTest() {
        // TODO: test sorter
    }

    /**
     * Test the property 'paginator'
     */
    @Test
    void paginatorTest() {
        // TODO: test paginator
    }

    /**
     * Test the property 'autocreateSearcheableStrings'
     */
    @Test
    void autocreateSearcheableStringsTest() {
        // TODO: test autocreateSearcheableStrings
    }

    /**
     * Test the property 'hints'
     */
    @Test
    void hintsTest() {
        // TODO: test hints
    }

    /**
     * Test the property 'depth'
     */
    @Test
    void depthTest() {
        // TODO: test depth
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    void maxResultsTest() {
        // TODO: test maxResults
    }

    /**
     * Test the property 'sortedKeys'
     */
    @Test
    void sortedKeysTest() {
        // TODO: test sortedKeys
    }

    /**
     * Test the property 'sorted'
     */
    @Test
    void sortedTest() {
        // TODO: test sorted
    }

    /**
     * Test the property 'empty'
     */
    @Test
    void emptyTest() {
        // TODO: test empty
    }

}
