/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import tools.dynamia.clients.model.ActionRef;
import tools.dynamia.clients.model.Field;
import tools.dynamia.clients.model.FieldGroup;
import tools.dynamia.clients.model.ViewLayout;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ViewDescriptor
 */
class ViewDescriptorTest {
    private final ViewDescriptor model = new ViewDescriptor();

    /**
     * Model tests for ViewDescriptor
     */
    @Test
    void testViewDescriptor() {
        // TODO: test ViewDescriptor
    }

    /**
     * Test the property 'fields'
     */
    @Test
    void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'actions'
     */
    @Test
    void actionsTest() {
        // TODO: test actions
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'layout'
     */
    @Test
    void layoutTest() {
        // TODO: test layout
    }

    /**
     * Test the property '_extends'
     */
    @Test
    void _extendsTest() {
        // TODO: test _extends
    }

    /**
     * Test the property 'autofields'
     */
    @Test
    void autofieldsTest() {
        // TODO: test autofields
    }

    /**
     * Test the property 'device'
     */
    @Test
    void deviceTest() {
        // TODO: test device
    }

    /**
     * Test the property 'viewTypeName'
     */
    @Test
    void viewTypeNameTest() {
        // TODO: test viewTypeName
    }

    /**
     * Test the property 'messages'
     */
    @Test
    void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'fieldGroups'
     */
    @Test
    void fieldGroupsTest() {
        // TODO: test fieldGroups
    }

    /**
     * Test the property 'params'
     */
    @Test
    void paramsTest() {
        // TODO: test params
    }

}
