/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.api;

import tools.dynamia.clients.model.QueryParameters;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DynamiaCrudServiceApi
 */
@Disabled
public class DynamiaCrudServiceApiTest {

    private final DynamiaCrudServiceApi api = new DynamiaCrudServiceApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void createOrSaveTest()  {
        String className = null;
        String body = null;
        Object response = api.createOrSave(className, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void createOrSave1Test()  {
        String className = null;
        String body = null;
        Object response = api.createOrSave1(className, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void deleteTest()  {
        String className = null;
        Object id = null;
        Object response = api.delete(className, id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void findTest()  {
        String className = null;
        QueryParameters queryParameters = null;
        List<Object> response = api.find(className, queryParameters);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getTest()  {
        String className = null;
        Object id = null;
        Object response = api.get(className, id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void getIdTest()  {
        String className = null;
        QueryParameters queryParameters = null;
        Object response = api.getId(className, queryParameters);

        // TODO: test validations
    }
    
}