/*
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tools.dynamia.clients.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DynamiaPeriodicTasksApi
 */
@Disabled
public class DynamiaPeriodicTasksApiTest {

    private final DynamiaPeriodicTasksApi api = new DynamiaPeriodicTasksApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void executeAfternoonTasksTest()  {
        api.executeAfternoonTasks();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void executeMiddayTasksTest()  {
        api.executeMiddayTasks();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void executeMidnightTasksTest()  {
        api.executeMidnightTasks();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void executeMorningTasksTest()  {
        api.executeMorningTasks();

        // TODO: test validations
    }
    
}