/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActionMetadata {
    'id'?: string;
    'name'?: string;
    'endpoint'?: string;
    'description'?: string;
    'icon'?: string;
    'group'?: string;
    'renderer'?: string;
    'applicableClasses'?: Array<string>;
    'applicableStates'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        },
        {
            "name": "renderer",
            "baseName": "renderer",
            "type": "string"
        },
        {
            "name": "applicableClasses",
            "baseName": "applicableClasses",
            "type": "Array<string>"
        },
        {
            "name": "applicableStates",
            "baseName": "applicableStates",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ActionMetadata.attributeTypeMap;
    }
}

