/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActionMetadata } from './actionMetadata';
import { ViewDescriptorMetadata } from './viewDescriptorMetadata';

export class EntityMetadata {
    'id'?: string;
    'name'?: string;
    'endpoint'?: string;
    'description'?: string;
    'icon'?: string;
    'className'?: string;
    'actions'?: Array<ActionMetadata>;
    'descriptors'?: Array<ViewDescriptorMetadata>;
    'actionsEndpoint'?: string;
    'viewsEndpoint'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "endpoint",
            "baseName": "endpoint",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "className",
            "baseName": "className",
            "type": "string"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<ActionMetadata>"
        },
        {
            "name": "descriptors",
            "baseName": "descriptors",
            "type": "Array<ViewDescriptorMetadata>"
        },
        {
            "name": "actionsEndpoint",
            "baseName": "actionsEndpoint",
            "type": "string"
        },
        {
            "name": "viewsEndpoint",
            "baseName": "viewsEndpoint",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntityMetadata.attributeTypeMap;
    }
}

