/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActionRef } from './actionRef';

export class Field {
    'name'?: string;
    'label'?: string;
    'description'?: string;
    'component'?: string;
    'params'?: { [key: string]: object; };
    'visible'?: boolean;
    'index'?: number;
    'required'?: boolean;
    'action'?: ActionRef;
    'icon'?: string;
    'showIconOnly'?: boolean;
    'optional'?: boolean;
    'path'?: string;
    'variable'?: string;
    'readOnly'?: boolean;
    'collection'?: boolean;
    'entity'?: boolean;
    'localizedDescription'?: string;
    'localizedLabel'?: string;
    'property'?: boolean;
    'readWrite'?: boolean;
    'writeOnly'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "component",
            "baseName": "component",
            "type": "string"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "ActionRef"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "showIconOnly",
            "baseName": "showIconOnly",
            "type": "boolean"
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "variable",
            "baseName": "variable",
            "type": "string"
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "boolean"
        },
        {
            "name": "collection",
            "baseName": "collection",
            "type": "boolean"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "boolean"
        },
        {
            "name": "localizedDescription",
            "baseName": "localizedDescription",
            "type": "string"
        },
        {
            "name": "localizedLabel",
            "baseName": "localizedLabel",
            "type": "string"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "boolean"
        },
        {
            "name": "readWrite",
            "baseName": "readWrite",
            "type": "boolean"
        },
        {
            "name": "writeOnly",
            "baseName": "writeOnly",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Field.attributeTypeMap;
    }
}

