/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FieldGroup {
    'name'?: string;
    'label'?: string;
    'description'?: string;
    'icon'?: string;
    'index'?: number;
    'collapse'?: boolean;
    'params'?: { [key: string]: object; };
    'localizedLabel'?: string;
    'fields'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "collapse",
            "baseName": "collapse",
            "type": "boolean"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "localizedLabel",
            "baseName": "localizedLabel",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FieldGroup.attributeTypeMap;
    }
}

