/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BeanSorterObject } from './beanSorterObject';
import { DataPaginator } from './dataPaginator';

export class QueryParameters extends object {
    'sorter'?: BeanSorterObject;
    'paginator'?: DataPaginator;
    'autocreateSearcheableStrings'?: boolean;
    'hints'?: { [key: string]: object; };
    'depth'?: number;
    'maxResults'?: number;
    'sortedKeys'?: Array<string>;
    'sorted'?: boolean;
    'empty'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sorter",
            "baseName": "sorter",
            "type": "BeanSorterObject"
        },
        {
            "name": "paginator",
            "baseName": "paginator",
            "type": "DataPaginator"
        },
        {
            "name": "autocreateSearcheableStrings",
            "baseName": "autocreateSearcheableStrings",
            "type": "boolean"
        },
        {
            "name": "hints",
            "baseName": "hints",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "depth",
            "baseName": "depth",
            "type": "number"
        },
        {
            "name": "maxResults",
            "baseName": "maxResults",
            "type": "number"
        },
        {
            "name": "sortedKeys",
            "baseName": "sortedKeys",
            "type": "Array<string>"
        },
        {
            "name": "sorted",
            "baseName": "sorted",
            "type": "boolean"
        },
        {
            "name": "empty",
            "baseName": "empty",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(QueryParameters.attributeTypeMap);
    }
}

