/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActionRef } from './actionRef';
import { Field } from './field';
import { FieldGroup } from './fieldGroup';
import { ViewLayout } from './viewLayout';

export class ViewDescriptor {
    'fields'?: Array<Field>;
    'actions'?: Array<ActionRef>;
    'id'?: string;
    'layout'?: ViewLayout;
    '_extends'?: string;
    'autofields'?: boolean;
    'device'?: string;
    'viewTypeName'?: string;
    'messages'?: string;
    'fieldGroups'?: Array<FieldGroup>;
    'params'?: { [key: string]: object; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<Field>"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<ActionRef>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "layout",
            "baseName": "layout",
            "type": "ViewLayout"
        },
        {
            "name": "_extends",
            "baseName": "extends",
            "type": "string"
        },
        {
            "name": "autofields",
            "baseName": "autofields",
            "type": "boolean"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "string"
        },
        {
            "name": "viewTypeName",
            "baseName": "viewTypeName",
            "type": "string"
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "string"
        },
        {
            "name": "fieldGroups",
            "baseName": "fieldGroups",
            "type": "Array<FieldGroup>"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "{ [key: string]: object; }"
        }    ];

    static getAttributeTypeMap() {
        return ViewDescriptor.attributeTypeMap;
    }
}

