/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ActionExecutionResponse {
  
  @SerializedName("data")
  private Object data = null;
  @SerializedName("params")
  private Map<String, Object> params = null;
  @SerializedName("source")
  private String source = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("statusCode")
  private Integer statusCode = null;
  @SerializedName("dataType")
  private String dataType = null;
  @SerializedName("dataId")
  private String dataId = null;
  @SerializedName("dataName")
  private String dataName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getData() {
    return data;
  }
  public void setData(Object data) {
    this.data = data;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getParams() {
    return params;
  }
  public void setParams(Map<String, Object> params) {
    this.params = params;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSource() {
    return source;
  }
  public void setSource(String source) {
    this.source = source;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStatusCode() {
    return statusCode;
  }
  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDataType() {
    return dataType;
  }
  public void setDataType(String dataType) {
    this.dataType = dataType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDataId() {
    return dataId;
  }
  public void setDataId(String dataId) {
    this.dataId = dataId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDataName() {
    return dataName;
  }
  public void setDataName(String dataName) {
    this.dataName = dataName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionExecutionResponse actionExecutionResponse = (ActionExecutionResponse) o;
    return (this.data == null ? actionExecutionResponse.data == null : this.data.equals(actionExecutionResponse.data)) &&
        (this.params == null ? actionExecutionResponse.params == null : this.params.equals(actionExecutionResponse.params)) &&
        (this.source == null ? actionExecutionResponse.source == null : this.source.equals(actionExecutionResponse.source)) &&
        (this.status == null ? actionExecutionResponse.status == null : this.status.equals(actionExecutionResponse.status)) &&
        (this.statusCode == null ? actionExecutionResponse.statusCode == null : this.statusCode.equals(actionExecutionResponse.statusCode)) &&
        (this.dataType == null ? actionExecutionResponse.dataType == null : this.dataType.equals(actionExecutionResponse.dataType)) &&
        (this.dataId == null ? actionExecutionResponse.dataId == null : this.dataId.equals(actionExecutionResponse.dataId)) &&
        (this.dataName == null ? actionExecutionResponse.dataName == null : this.dataName.equals(actionExecutionResponse.dataName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.data == null ? 0: this.data.hashCode());
    result = 31 * result + (this.params == null ? 0: this.params.hashCode());
    result = 31 * result + (this.source == null ? 0: this.source.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.statusCode == null ? 0: this.statusCode.hashCode());
    result = 31 * result + (this.dataType == null ? 0: this.dataType.hashCode());
    result = 31 * result + (this.dataId == null ? 0: this.dataId.hashCode());
    result = 31 * result + (this.dataName == null ? 0: this.dataName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionExecutionResponse {\n");
    
    sb.append("  data: ").append(data).append("\n");
    sb.append("  params: ").append(params).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  statusCode: ").append(statusCode).append("\n");
    sb.append("  dataType: ").append(dataType).append("\n");
    sb.append("  dataId: ").append(dataId).append("\n");
    sb.append("  dataName: ").append(dataName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
