/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ActionMetadata {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("endpoint")
  private String endpoint = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("icon")
  private String icon = null;
  @SerializedName("group")
  private String group = null;
  @SerializedName("renderer")
  private String renderer = null;
  @SerializedName("applicableClasses")
  private List<String> applicableClasses = null;
  @SerializedName("applicableStates")
  private List<String> applicableStates = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEndpoint() {
    return endpoint;
  }
  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGroup() {
    return group;
  }
  public void setGroup(String group) {
    this.group = group;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRenderer() {
    return renderer;
  }
  public void setRenderer(String renderer) {
    this.renderer = renderer;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getApplicableClasses() {
    return applicableClasses;
  }
  public void setApplicableClasses(List<String> applicableClasses) {
    this.applicableClasses = applicableClasses;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getApplicableStates() {
    return applicableStates;
  }
  public void setApplicableStates(List<String> applicableStates) {
    this.applicableStates = applicableStates;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionMetadata actionMetadata = (ActionMetadata) o;
    return (this.id == null ? actionMetadata.id == null : this.id.equals(actionMetadata.id)) &&
        (this.name == null ? actionMetadata.name == null : this.name.equals(actionMetadata.name)) &&
        (this.endpoint == null ? actionMetadata.endpoint == null : this.endpoint.equals(actionMetadata.endpoint)) &&
        (this.description == null ? actionMetadata.description == null : this.description.equals(actionMetadata.description)) &&
        (this.icon == null ? actionMetadata.icon == null : this.icon.equals(actionMetadata.icon)) &&
        (this.group == null ? actionMetadata.group == null : this.group.equals(actionMetadata.group)) &&
        (this.renderer == null ? actionMetadata.renderer == null : this.renderer.equals(actionMetadata.renderer)) &&
        (this.applicableClasses == null ? actionMetadata.applicableClasses == null : this.applicableClasses.equals(actionMetadata.applicableClasses)) &&
        (this.applicableStates == null ? actionMetadata.applicableStates == null : this.applicableStates.equals(actionMetadata.applicableStates));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.endpoint == null ? 0: this.endpoint.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.icon == null ? 0: this.icon.hashCode());
    result = 31 * result + (this.group == null ? 0: this.group.hashCode());
    result = 31 * result + (this.renderer == null ? 0: this.renderer.hashCode());
    result = 31 * result + (this.applicableClasses == null ? 0: this.applicableClasses.hashCode());
    result = 31 * result + (this.applicableStates == null ? 0: this.applicableStates.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionMetadata {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  endpoint: ").append(endpoint).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  group: ").append(group).append("\n");
    sb.append("  renderer: ").append(renderer).append("\n");
    sb.append("  applicableClasses: ").append(applicableClasses).append("\n");
    sb.append("  applicableStates: ").append(applicableStates).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
