/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ApplicationMetadata {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("endpoint")
  private String endpoint = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("icon")
  private String icon = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("version")
  private String version = null;
  @SerializedName("logo")
  private String logo = null;
  @SerializedName("template")
  private String template = null;
  @SerializedName("author")
  private String author = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEndpoint() {
    return endpoint;
  }
  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogo() {
    return logo;
  }
  public void setLogo(String logo) {
    this.logo = logo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTemplate() {
    return template;
  }
  public void setTemplate(String template) {
    this.template = template;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationMetadata applicationMetadata = (ApplicationMetadata) o;
    return (this.id == null ? applicationMetadata.id == null : this.id.equals(applicationMetadata.id)) &&
        (this.name == null ? applicationMetadata.name == null : this.name.equals(applicationMetadata.name)) &&
        (this.endpoint == null ? applicationMetadata.endpoint == null : this.endpoint.equals(applicationMetadata.endpoint)) &&
        (this.description == null ? applicationMetadata.description == null : this.description.equals(applicationMetadata.description)) &&
        (this.icon == null ? applicationMetadata.icon == null : this.icon.equals(applicationMetadata.icon)) &&
        (this.title == null ? applicationMetadata.title == null : this.title.equals(applicationMetadata.title)) &&
        (this.version == null ? applicationMetadata.version == null : this.version.equals(applicationMetadata.version)) &&
        (this.logo == null ? applicationMetadata.logo == null : this.logo.equals(applicationMetadata.logo)) &&
        (this.template == null ? applicationMetadata.template == null : this.template.equals(applicationMetadata.template)) &&
        (this.author == null ? applicationMetadata.author == null : this.author.equals(applicationMetadata.author));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.endpoint == null ? 0: this.endpoint.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.icon == null ? 0: this.icon.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.version == null ? 0: this.version.hashCode());
    result = 31 * result + (this.logo == null ? 0: this.logo.hashCode());
    result = 31 * result + (this.template == null ? 0: this.template.hashCode());
    result = 31 * result + (this.author == null ? 0: this.author.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationMetadata {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  endpoint: ").append(endpoint).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("  logo: ").append(logo).append("\n");
    sb.append("  template: ").append(template).append("\n");
    sb.append("  author: ").append(author).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
