/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import tools.dynamia.clients.model.ActionMetadata;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ApplicationMetadataActions {
  
  @SerializedName("actions")
  private List<ActionMetadata> actions = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ActionMetadata> getActions() {
    return actions;
  }
  public void setActions(List<ActionMetadata> actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationMetadataActions applicationMetadataActions = (ApplicationMetadataActions) o;
    return (this.actions == null ? applicationMetadataActions.actions == null : this.actions.equals(applicationMetadataActions.actions));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.actions == null ? 0: this.actions.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationMetadataActions {\n");
    
    sb.append("  actions: ").append(actions).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
