/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import tools.dynamia.clients.model.EntityMetadata;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ApplicationMetadataEntities {
  
  @SerializedName("entities")
  private List<EntityMetadata> entities = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<EntityMetadata> getEntities() {
    return entities;
  }
  public void setEntities(List<EntityMetadata> entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationMetadataEntities applicationMetadataEntities = (ApplicationMetadataEntities) o;
    return (this.entities == null ? applicationMetadataEntities.entities == null : this.entities.equals(applicationMetadataEntities.entities));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.entities == null ? 0: this.entities.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationMetadataEntities {\n");
    
    sb.append("  entities: ").append(entities).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
