/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BeanSorterObject {
  
  @SerializedName("ascending")
  private Boolean ascending = null;
  @SerializedName("columnName")
  private String columnName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAscending() {
    return ascending;
  }
  public void setAscending(Boolean ascending) {
    this.ascending = ascending;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getColumnName() {
    return columnName;
  }
  public void setColumnName(String columnName) {
    this.columnName = columnName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeanSorterObject beanSorterObject = (BeanSorterObject) o;
    return (this.ascending == null ? beanSorterObject.ascending == null : this.ascending.equals(beanSorterObject.ascending)) &&
        (this.columnName == null ? beanSorterObject.columnName == null : this.columnName.equals(beanSorterObject.columnName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ascending == null ? 0: this.ascending.hashCode());
    result = 31 * result + (this.columnName == null ? 0: this.columnName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeanSorterObject {\n");
    
    sb.append("  ascending: ").append(ascending).append("\n");
    sb.append("  columnName: ").append(columnName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
