/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DataPaginator {
  
  @SerializedName("totalSize")
  private Long totalSize = null;
  @SerializedName("pageSize")
  private Integer pageSize = null;
  @SerializedName("firstResult")
  private Integer firstResult = null;
  @SerializedName("page")
  private Integer page = null;
  @SerializedName("pagesNumber")
  private Integer pagesNumber = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTotalSize() {
    return totalSize;
  }
  public void setTotalSize(Long totalSize) {
    this.totalSize = totalSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPageSize() {
    return pageSize;
  }
  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getFirstResult() {
    return firstResult;
  }
  public void setFirstResult(Integer firstResult) {
    this.firstResult = firstResult;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPage() {
    return page;
  }
  public void setPage(Integer page) {
    this.page = page;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPagesNumber() {
    return pagesNumber;
  }
  public void setPagesNumber(Integer pagesNumber) {
    this.pagesNumber = pagesNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataPaginator dataPaginator = (DataPaginator) o;
    return (this.totalSize == null ? dataPaginator.totalSize == null : this.totalSize.equals(dataPaginator.totalSize)) &&
        (this.pageSize == null ? dataPaginator.pageSize == null : this.pageSize.equals(dataPaginator.pageSize)) &&
        (this.firstResult == null ? dataPaginator.firstResult == null : this.firstResult.equals(dataPaginator.firstResult)) &&
        (this.page == null ? dataPaginator.page == null : this.page.equals(dataPaginator.page)) &&
        (this.pagesNumber == null ? dataPaginator.pagesNumber == null : this.pagesNumber.equals(dataPaginator.pagesNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.totalSize == null ? 0: this.totalSize.hashCode());
    result = 31 * result + (this.pageSize == null ? 0: this.pageSize.hashCode());
    result = 31 * result + (this.firstResult == null ? 0: this.firstResult.hashCode());
    result = 31 * result + (this.page == null ? 0: this.page.hashCode());
    result = 31 * result + (this.pagesNumber == null ? 0: this.pagesNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataPaginator {\n");
    
    sb.append("  totalSize: ").append(totalSize).append("\n");
    sb.append("  pageSize: ").append(pageSize).append("\n");
    sb.append("  firstResult: ").append(firstResult).append("\n");
    sb.append("  page: ").append(page).append("\n");
    sb.append("  pagesNumber: ").append(pagesNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
