/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import java.util.Map;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FieldGroup {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("label")
  private String label = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("icon")
  private String icon = null;
  @SerializedName("index")
  private Integer index = null;
  @SerializedName("collapse")
  private Boolean collapse = null;
  @SerializedName("params")
  private Map<String, Object> params = null;
  @SerializedName("localizedLabel")
  private String localizedLabel = null;
  @SerializedName("fields")
  private List<String> fields = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getIndex() {
    return index;
  }
  public void setIndex(Integer index) {
    this.index = index;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getCollapse() {
    return collapse;
  }
  public void setCollapse(Boolean collapse) {
    this.collapse = collapse;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getParams() {
    return params;
  }
  public void setParams(Map<String, Object> params) {
    this.params = params;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocalizedLabel() {
    return localizedLabel;
  }
  public void setLocalizedLabel(String localizedLabel) {
    this.localizedLabel = localizedLabel;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getFields() {
    return fields;
  }
  public void setFields(List<String> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldGroup fieldGroup = (FieldGroup) o;
    return (this.name == null ? fieldGroup.name == null : this.name.equals(fieldGroup.name)) &&
        (this.label == null ? fieldGroup.label == null : this.label.equals(fieldGroup.label)) &&
        (this.description == null ? fieldGroup.description == null : this.description.equals(fieldGroup.description)) &&
        (this.icon == null ? fieldGroup.icon == null : this.icon.equals(fieldGroup.icon)) &&
        (this.index == null ? fieldGroup.index == null : this.index.equals(fieldGroup.index)) &&
        (this.collapse == null ? fieldGroup.collapse == null : this.collapse.equals(fieldGroup.collapse)) &&
        (this.params == null ? fieldGroup.params == null : this.params.equals(fieldGroup.params)) &&
        (this.localizedLabel == null ? fieldGroup.localizedLabel == null : this.localizedLabel.equals(fieldGroup.localizedLabel)) &&
        (this.fields == null ? fieldGroup.fields == null : this.fields.equals(fieldGroup.fields));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.label == null ? 0: this.label.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.icon == null ? 0: this.icon.hashCode());
    result = 31 * result + (this.index == null ? 0: this.index.hashCode());
    result = 31 * result + (this.collapse == null ? 0: this.collapse.hashCode());
    result = 31 * result + (this.params == null ? 0: this.params.hashCode());
    result = 31 * result + (this.localizedLabel == null ? 0: this.localizedLabel.hashCode());
    result = 31 * result + (this.fields == null ? 0: this.fields.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldGroup {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  label: ").append(label).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  index: ").append(index).append("\n");
    sb.append("  collapse: ").append(collapse).append("\n");
    sb.append("  params: ").append(params).append("\n");
    sb.append("  localizedLabel: ").append(localizedLabel).append("\n");
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
