/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import tools.dynamia.clients.model.NavigationNode;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class NavigationTree {
  
  @SerializedName("navigation")
  private List<NavigationNode> navigation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<NavigationNode> getNavigation() {
    return navigation;
  }
  public void setNavigation(List<NavigationNode> navigation) {
    this.navigation = navigation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NavigationTree navigationTree = (NavigationTree) o;
    return (this.navigation == null ? navigationTree.navigation == null : this.navigation.equals(navigationTree.navigation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.navigation == null ? 0: this.navigation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NavigationTree {\n");
    
    sb.append("  navigation: ").append(navigation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
