/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import java.util.*;
import java.util.Map;
import tools.dynamia.clients.model.ActionRef;
import tools.dynamia.clients.model.Field;
import tools.dynamia.clients.model.FieldGroup;
import tools.dynamia.clients.model.ViewLayout;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ViewDescriptor {
  
  @SerializedName("fields")
  private List<Field> fields = null;
  @SerializedName("actions")
  private List<ActionRef> actions = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("layout")
  private ViewLayout layout = null;
  @SerializedName("extends")
  private String _extends = null;
  @SerializedName("autofields")
  private Boolean autofields = null;
  @SerializedName("device")
  private String device = null;
  @SerializedName("viewTypeName")
  private String viewTypeName = null;
  @SerializedName("messages")
  private String messages = null;
  @SerializedName("fieldGroups")
  private List<FieldGroup> fieldGroups = null;
  @SerializedName("params")
  private Map<String, Object> params = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Field> getFields() {
    return fields;
  }
  public void setFields(List<Field> fields) {
    this.fields = fields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ActionRef> getActions() {
    return actions;
  }
  public void setActions(List<ActionRef> actions) {
    this.actions = actions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ViewLayout getLayout() {
    return layout;
  }
  public void setLayout(ViewLayout layout) {
    this.layout = layout;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExtends() {
    return _extends;
  }
  public void setExtends(String _extends) {
    this._extends = _extends;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getAutofields() {
    return autofields;
  }
  public void setAutofields(Boolean autofields) {
    this.autofields = autofields;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDevice() {
    return device;
  }
  public void setDevice(String device) {
    this.device = device;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getViewTypeName() {
    return viewTypeName;
  }
  public void setViewTypeName(String viewTypeName) {
    this.viewTypeName = viewTypeName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMessages() {
    return messages;
  }
  public void setMessages(String messages) {
    this.messages = messages;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<FieldGroup> getFieldGroups() {
    return fieldGroups;
  }
  public void setFieldGroups(List<FieldGroup> fieldGroups) {
    this.fieldGroups = fieldGroups;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getParams() {
    return params;
  }
  public void setParams(Map<String, Object> params) {
    this.params = params;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewDescriptor viewDescriptor = (ViewDescriptor) o;
    return (this.fields == null ? viewDescriptor.fields == null : this.fields.equals(viewDescriptor.fields)) &&
        (this.actions == null ? viewDescriptor.actions == null : this.actions.equals(viewDescriptor.actions)) &&
        (this.id == null ? viewDescriptor.id == null : this.id.equals(viewDescriptor.id)) &&
        (this.layout == null ? viewDescriptor.layout == null : this.layout.equals(viewDescriptor.layout)) &&
        (this._extends == null ? viewDescriptor._extends == null : this._extends.equals(viewDescriptor._extends)) &&
        (this.autofields == null ? viewDescriptor.autofields == null : this.autofields.equals(viewDescriptor.autofields)) &&
        (this.device == null ? viewDescriptor.device == null : this.device.equals(viewDescriptor.device)) &&
        (this.viewTypeName == null ? viewDescriptor.viewTypeName == null : this.viewTypeName.equals(viewDescriptor.viewTypeName)) &&
        (this.messages == null ? viewDescriptor.messages == null : this.messages.equals(viewDescriptor.messages)) &&
        (this.fieldGroups == null ? viewDescriptor.fieldGroups == null : this.fieldGroups.equals(viewDescriptor.fieldGroups)) &&
        (this.params == null ? viewDescriptor.params == null : this.params.equals(viewDescriptor.params));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fields == null ? 0: this.fields.hashCode());
    result = 31 * result + (this.actions == null ? 0: this.actions.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.layout == null ? 0: this.layout.hashCode());
    result = 31 * result + (this._extends == null ? 0: this._extends.hashCode());
    result = 31 * result + (this.autofields == null ? 0: this.autofields.hashCode());
    result = 31 * result + (this.device == null ? 0: this.device.hashCode());
    result = 31 * result + (this.viewTypeName == null ? 0: this.viewTypeName.hashCode());
    result = 31 * result + (this.messages == null ? 0: this.messages.hashCode());
    result = 31 * result + (this.fieldGroups == null ? 0: this.fieldGroups.hashCode());
    result = 31 * result + (this.params == null ? 0: this.params.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewDescriptor {\n");
    
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("  actions: ").append(actions).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  layout: ").append(layout).append("\n");
    sb.append("  _extends: ").append(_extends).append("\n");
    sb.append("  autofields: ").append(autofields).append("\n");
    sb.append("  device: ").append(device).append("\n");
    sb.append("  viewTypeName: ").append(viewTypeName).append("\n");
    sb.append("  messages: ").append(messages).append("\n");
    sb.append("  fieldGroups: ").append(fieldGroups).append("\n");
    sb.append("  params: ").append(params).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
