/**
 * DynamiaTools API
 * DynamiaTools Metadata API
 *
 * The version of the OpenAPI document: 5.3.6
 * Contact: mario@dynamiasoluciones.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package tools.dynamia.clients.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ViewDescriptorMetadata {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("endpoint")
  private String endpoint = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("icon")
  private String icon = null;
  @SerializedName("view")
  private String view = null;
  @SerializedName("device")
  private String device = null;
  @SerializedName("beanClass")
  private String beanClass = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEndpoint() {
    return endpoint;
  }
  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getView() {
    return view;
  }
  public void setView(String view) {
    this.view = view;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDevice() {
    return device;
  }
  public void setDevice(String device) {
    this.device = device;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBeanClass() {
    return beanClass;
  }
  public void setBeanClass(String beanClass) {
    this.beanClass = beanClass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewDescriptorMetadata viewDescriptorMetadata = (ViewDescriptorMetadata) o;
    return (this.id == null ? viewDescriptorMetadata.id == null : this.id.equals(viewDescriptorMetadata.id)) &&
        (this.name == null ? viewDescriptorMetadata.name == null : this.name.equals(viewDescriptorMetadata.name)) &&
        (this.endpoint == null ? viewDescriptorMetadata.endpoint == null : this.endpoint.equals(viewDescriptorMetadata.endpoint)) &&
        (this.description == null ? viewDescriptorMetadata.description == null : this.description.equals(viewDescriptorMetadata.description)) &&
        (this.icon == null ? viewDescriptorMetadata.icon == null : this.icon.equals(viewDescriptorMetadata.icon)) &&
        (this.view == null ? viewDescriptorMetadata.view == null : this.view.equals(viewDescriptorMetadata.view)) &&
        (this.device == null ? viewDescriptorMetadata.device == null : this.device.equals(viewDescriptorMetadata.device)) &&
        (this.beanClass == null ? viewDescriptorMetadata.beanClass == null : this.beanClass.equals(viewDescriptorMetadata.beanClass));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.endpoint == null ? 0: this.endpoint.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.icon == null ? 0: this.icon.hashCode());
    result = 31 * result + (this.view == null ? 0: this.view.hashCode());
    result = 31 * result + (this.device == null ? 0: this.device.hashCode());
    result = 31 * result + (this.beanClass == null ? 0: this.beanClass.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewDescriptorMetadata {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  endpoint: ").append(endpoint).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  view: ").append(view).append("\n");
    sb.append("  device: ").append(device).append("\n");
    sb.append("  beanClass: ").append(beanClass).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
